reads: # Specify the order and methods for each read processing step. If no method is specified, the step will not be performed.
  subsampling: null # null/enum: Subsampling method, if not set, subsampling will not be performed. Allowed: 'seqtk'.
  trimming: "cutadapt" # null/enum: Trimming method, if not set, trimming will not be performed. Allowed: 'cutadapt'.
  decontamination: "bwa" # null/enum: Decontamination method, if not set, decontamination will not be performed. Allowed: 'kraken'.
  deduplication: null # null/enum: Deduplication method, if not set, deduplication will not be performed. Allowed: 'fastuniq'.
  _generate_fastqc_for: ["trimming"] # list of enum: Specify which steps to generate fastqc for. Allowed: 'original','subsampling','trimming','decontamination','deduplication'.

mapping:
  _input: "assembly" # enum(reads): Input data for mapping. Allowed: 'reads' or 'assembly'.
  mapping: "minimap2" # Specify method for mapping. Allowed: "bwa".
  reference_fasta_paths: ["test_data/reference/sars_cov_2/sars_cov_2.fa"] # specify list of reference dirs to map against. Each dir must contain a fasta file names as the basename dir.
  deduplication: "samtools" # OPT - specify method for mapping deduplication. Allowed: "picard", null.
  _generate_qualimap: true

assembly: # Uses processed reads. If no assembly method is specified, the step will not be performed.
  assembly: "spades" # enum: Assembly tool to use. Allowed: 'spades'.
  report: ["quast", "bandage"] # list of enum([]): Reporting tool for assembly QC. Allowed: 'bandage','quast'.
  classification: ["blast"] # list of enum([]): Classification method to use for contigs. Allowed: 'blast'.

### HYPERPARAMETERS #############################

reads__subsampling__seqtk:
  seed: 1
  n_reads: 1
  reduce_memory: true

reads__trimming__cutadapt: # Relevant only if reads->trimming is set to cutadapt.
  cut_from_start_r1: null # null/int: Removes a specified number of bases from the beginning of the R1 read.
  cut_from_start_r2: null # null/int: Removes a specified number of bases from the beginning of the R2 read.
  cut_from_end_r1: null # null/int: Removes a specified number of bases from the end of the R1 read.
  cut_from_end_r2: null # null/int: Removes a specified number of bases from the end of the R2 read.
  quality_cutoff_from_3_end_r1: 20 # int(20): Removes lower quality bases from the 3' end of the R1 read.
  quality_cutoff_from_5_end_r1: 20 # int(20): Removes lower quality bases from the 5' end of the R1 read.
  quality_cutoff_from_3_end_r2: 20 # int(20): Removes lower quality bases from the 3' end of the R2 read.
  quality_cutoff_from_5_end_r2: 20 # int(20): Removes lower quality bases from the 5' end of the R2 read.
  nextseq_trimming_mode: false # bool(false): Modify quality-trimming algorithm to expect two-color chemistry data (NextSeq).
  do_adapter_removal: false # bool(false): Whether to do adapter removal or not.
  adapter_removal: # Relevant only if do_adapter_removal is set to true.
    action: "trim" # enum(trim): Defines an action to perform with the found adapter. Allowed: 'retain','trim','mask','none','lowercase'.
    overlap: 3 # int(3): Minimum number of bases required to overlap with the adapter.
    error_rate: 0.1 # float(0.1): Error tolerance used when searching for adapter.
    times: 1 # int(1): How many times to repeat adapter removal.
    keep_trimmed_only: false # bool(false): Discard reads with no adapters found.
    adapters_anywhere_file: "test_data/adapters/artic_v4.fa" # null/str: Fasta file path with adapters to be matched 'anywhere'.
    adapters_3_end_file: null # null/str: Fasta file path with adapters to be matched at 3'end.
    adapters_5_end_file: null # null/str: Fasta file path with adapters to be matched at 5'end.
  shorten_to_length: 500 # null/int: Shorten each read to the specified length. Corresponds to the cutadapt length parameter.
  shorten_to_length_r2: 550 # null/int: Shorten each R2 read to the specified length. If not specified, 'shorten_to_length' is applied for R2 as well.
  trim_N_bases_on_ends: false # bool(false): Set to true to trim 'N' bases on ends.
  min_length_r1: null # null/int: Discards R1 reads shorter than this. Recommended to set at least to 1, to discard empty reads.
  min_length_r2: null # null/int: Discards R2 reads shorter than this. Recommended to set at least to 1, to discard empty reads.
  max_length_r1: null # null/int: Discards R1 reads longer than this value.
  max_length_r2: null # null/int: Discards R2 reads longer than this value.
  max_n_bases: null # null/int: Removes reads with more 'N' bases than the specified number.
  max_expected_errors: 5 # null/int: Discard reads whose expected number of errors exceeds this value.
  max_average_error_rate: 0.8 # null/float: Discard reads whose average error rate exceeds this value. Between 0 and 1.

reads__decontamination__kraken:
  kraken_dir: "path_to_kraken/k2_viral_20230314" # Directory containing kraken DB files. If does not exist, will be downloaded using the dirname.
  # get KRAKEN_TAG from https://benlangmead.github.io/aws-indexes/k2
  taxa_ids: # list of taxonomy IDs to exclude.
    - 9606 # Homo Sapiens
  filter_mode: "exclude"
  filter_children: false # Whether to exclude reads classified at more specific levels than specified taxonomy ID levels.
  filter_ancestors: false # Whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels.
  save_memory: true # If true, kraken limits RAM memory usage but sacrifices speed.
  generate_krona: false # If true, krona is generated from kraken report
  krona_dir: null #"path_to_krona/{TIMESTAMP}"

reads__decontamination__bwa: # Relevant only if reads->decontamination is set to bwa.
  references: # list of min 1 str: List of reference fasta files.
    - "test_data/test_ref.fa"
  filter_mode: "exclude" # enum(exclude): Mapped reads are either excluded or included. Allowed: 'include','exclude'.

mapping__mapping__minimap2: # Relevant only if mapping->mapping is set to minimap2.
  preset: "splice" # enum: Mapping preset options. Allowed: 'sr', 'map-ont', 'map-hifi', 'map-pb', 'asm5', 'asm10', 'asm20', 'splice', 'splice:hq', 'splice:sr', 'ava-pb', 'ava-ont', 'lr:hq', 'map-iclr'.

assembly__assembly__spades:
  mode: "meta" # enum(standard): if true, kraken limits RAM memory usage but sacrifices speed Allowed: 'standard','meta','plasmid','metaplasmid','metaviral','bio','rna','rnaviral'.
  careful: false # bool(false): When set to true, spades tries to reduce number of mismatches and short indels, but it has longer runtime.

assembly__report__quast:
  min_contig_length: 500 # Default: 500. Minimum length in bp for contigs to be taken into account.
  extra: "" # Optional. Default: "". Provide directly arguments for quast. See https://quast.sourceforge.net/docs/manual.html

assembly__classification__blast: # Optional section (set to [] or remove). Here provide multiple dicts, one for each reference.
  # Use Blast DB tag, allowed: "18S_fungal_sequences" "Betacoronavirus" "ref_viroids_rep_genomes" "ref_viruses_rep_genomes" "refseq_select_rna" "refseq_select_prot" "refseq_protein" "refseq_rna" "16S_ribosomal_RNA" "ITS_RefSeq_Fungi" "28S_fungal_sequences" "ITS_eukaryote_sequences" "LSU_eukaryote_rRNA" "LSU_prokaryote_rRNA" "SSU_eukaryote_rRNA" "env_nt" "env_nr" "human_genome" "landmark" "mito" "mouse_genome" "nr" "nt_euk" "nt" "nt_others" "swissprot" "tsa_nr" "tsa_nt" "taxdb" "nt_prok" "nt_viruses" "pataa" "patnt" "pdbaa" "pdbnt" "ref_euk_rep_genomes" "ref_prok_rep_genomes".
  db_dir: "/data/genome/blast/18S_fungal_sequences/23-12-12" # where the DB is located or where it will be downloaded.
  query_vs_db: "nucleotide-nucleotide" # Type of query vs DB sequence (Searching nucleotide in nucleotide DB). Allowed: "nucleotide-nucleotide", "nucleotide-protein", "protein-protein", "protein-nucleotide".
  max_number_of_hits: 5 # Maximum number of best hits when blast querying an input sequence (default: 5).
  max_query_seqs: 2000 # Maximal number of contigs to report, ordered by their length (default: 2000).
  max_target_seqs: 5 # Maximal number of homologues from reference genomes to report (default: 5).
  min_query_coverage: 0.01 # Show only hits that have at least this proportion of contig mapped to reference (default: 0.01).
  seqs_per_page: 100 # Number of table rows (sequences) per page (default: 100)

### RESOURCES #############################

max_threads: 2
max_mem_mb: 6192

resources:
  reads__trimming_mem_mb: 4096
  reads__fastqc_mem_mb: 2048
  mapping__mapping_mem_mb: 4096
  mapping__indexing_mem_mb: 4096
  mapping__deduplication_mem_mb: 4096
  mapping__qualimap_mem_mb: 4096
  assembly__assembly_mem_mb: 64000 # Memory in MB to reserve for assembly

threads:
  reads__trimming: 4
  reads__fastqc: 1
  reads__deduplication: 4
  reads__decontamination: 8
  mapping__mapping: 2
  mapping__indexing: 2
  assembly__assembly: 16 # Number of threads to use for assembly.

module_versions:
  reads: "v3.7.0"
