"$schema": http://json-schema.org/draft-07/schema#
"$ref": "#/definitions/MappingWorkflow"
definitions:
  MappingWorkflow:
    type: object
    additionalProperties: true
    properties:
      mapping:
        type: object
        "$ref": "#/definitions/Mapping"
        default: {}
      resources:
        type: object
        "$ref": "#/definitions/Resources"
        default: {}
      threads:
        type: object
        "$ref": "#/definitions/Threads"
        default: {}
    title: MappingWorkflow
  Mapping:
    additionalProperties: false
    title: Mapping
    properties:
      mapping:
        type: string
        description: "Mapping tool to use for mapping."
        enum:
          - "bwa"
      reference_dirs:
        type: array
        description: "Paths to the reference directory."
        items:
          type: string
        minitems: 1
      deduplication:
        type: [string, "null"]
        description: "Deduplication method to use."
        enum:
          - "picard"
          - null
      _generate_qualimap:
        type: array
        description: "Steps to generate qualimap for."
        default: []
        items:
          type: string
          enum:
            - "mapping"
            - "deduplication"
    required:
      - mapping
      - reference_dirs
  Resources:
    additionalProperties: true
    mapping__mapping_mem_mb:
      type: integer
      description: "Memory in MB to reserve for mapping"
    mapping__indexing_mem_mb:
      type: integer
      description: "Memory in MB to reserve for bam_index"
    mapping__deduplication_mem_mb:
      type: integer
      description: "Memory in MB to reserve for picard"
    mapping__qualimap_mem_mb:
      type: integer
      description: "Memory in MB to reserve for qualimap"
    required:
      - mapping__mapping_mem_mb
      - mapping__indexing_mem_mb
      - mapping__deduplication_mem_mb
      - mapping__qualimap_mem_mb
    title: Resources
  Threads:
    additionalProperties: true
    mapping__mapping:
      type: integer
      default: 1
      description: "Number of threads to use for mapping"
    mapping__index:
      type: integer
      default: 1
      description: "Number of threads to use for bam_index"
    title: Threads
    required:
      - mapping__mapping
      - mapping__indexing
