"$schema": https://json-schema.org/draft/2020-12/schema
"$ref": "#/definitions/MappingWorkflow"
definitions:
  MappingWorkflow:
    type: object
    additionalProperties: true
    properties:
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs"
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job"
      mapping:
        type: object
        "$ref": "#/definitions/Mapping"
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
    required:
      - max_threads
      - max_mem_mb
      - mapping
      - resources
      - threads
    title: MappingWorkflow
    allOf:
      - if:
          properties:
            mapping:
              properties:
                deduplication:
                  type: string
        then:
          properties:
            resources:
              required:
                - mapping__deduplication_mem_mb
      - if:
          properties:
            mapping:
              properties:
                _generate_qualimap:
                  minItems: 1
        then:
          properties:
            resources:
              required:
                - mapping__qualimap_mem_mb
  Mapping:
    additionalProperties: false
    title: Mapping
    properties:
      mapping:
        type: string
        description: "Mapping tool to use for mapping."
        enum:
          - "bwa"
      reference_dirs:
        type: array
        description: "Paths to the reference directory. Each directory must contain a fasta file named as the basename of the directory."
        items:
          type: string
        minItems: 1
      deduplication:
        type: [string, "null"]
        description: "Optional. Deduplication method to use."
        enum:
          - "picard"
          - null
      _generate_qualimap:
        type: array
        description: "Steps to generate qualimap for."
        default: []
        items:
          type: string
          enum:
            - "mapping"
            - "deduplication"
    required:
      - mapping
      - reference_dirs
    allOf:
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "deduplication"
        then:
          properties:
            deduplication:
              type: string
              description: "Mapping->Deduplication is required if qualimap is requested for deduplication"
  Resources:
    additionalProperties: true
    properties:
      mapping__mapping_mem_mb:
        type: integer
        description: "Memory in MB to reserve for mapping"
      mapping__indexing_mem_mb:
        type: integer
        description: "Memory in MB to reserve for bam_index"
      mapping__deduplication_mem_mb:
        type: integer
        description: "Memory in MB to reserve for picard"
      mapping__qualimap_mem_mb:
        type: integer
        description: "Memory in MB to reserve for qualimap"
    required:
      - mapping__mapping_mem_mb
      - mapping__indexing_mem_mb
    title: Resources
  Threads:
    additionalProperties: true
    properties:
      mapping__mapping:
        type: integer
        default: 1
        description: "Number of threads to use for mapping"
      mapping__indexing:
        type: integer
        default: 1
        description: "Number of threads to use for bam_index"
    title: Threads
    required:
      - mapping__mapping
      - mapping__indexing
